In [7]:
import numpy as np
import argparse
import time
import cv2
import os
from keras.preprocessing import image
import matplotlib.pyplot as plt
from IPython.display import Image
from gtts import gTTS

In [8]:
video=cv2.VideoCapture(0)
check,frame=video.read()

print(check)
print(frame)

cv2.imshow("capt",frame)
img1=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
path="C:\\Users\\Hp\\Desktop\\"
cv2.imwrite(os.path.join(path , 'waka.jpg'), img1)
#cv2.waitKey(0)
video.release()
cv2.destroyAllWindows()


True
[[[  5  86 192]
  [  5  86 192]
  [  9  88 188]
  ...
  [  0  37 115]
  [  0  35 105]
  [  0  43 113]]

 [[  3  88 187]
  [  2  86 186]
  [  3  87 190]
  ...
  [  0  32 112]
  [  0  33 105]
  [  0  36 109]]

 [[  3  88 185]
  [  8  93 190]
  [ 10  89 191]
  ...
  [  0  33 110]
  [  0  32 104]
  [  0  33 105]]

 ...

 [[  0  18  75]
  [  6  32  89]
  [  0  32 152]
  ...
  [  0  56 153]
  [  0  56 155]
  [  0  54 152]]

 [[  0  23  92]
  [  3  39 109]
  [  0  43 159]
  ...
  [  0  54 148]
  [  0  58 154]
  [  0  54 149]]

 [[  0  33 118]
  [  2  44 129]
  [  0  45 173]
  ...
  [  0  58 146]
  [  0  57 150]
  [  0  51 144]]]


In [9]:
labelsPath = "C:\\Users\\Hp\\Desktop\\y\\coco.names"
LABELS = open(labelsPath).read().strip().split("\n")
COLORS = np.random.randint(0, 255, size=(len(LABELS), 3),
	dtype="uint8")
weightsPath = "C:\\Users\Hp\\Desktop\\y\\yolov3.weights"
configPath = "C:\\Users\\Hp\\Desktop\\y\\yolov3.cfg"
net = cv2.dnn.readNetFromDarknet(configPath, weightsPath)

In [10]:
  pathh ="C:\\Users\\Hp\\Desktop\\waka.jpg"
  image =cv2.imread(pathh)
  (H, W) = image.shape[:2]
  ln = net.getLayerNames()
  ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  blob = cv2.dnn.blobFromImage(image, 1 / 255.0, (416, 416),
  swapRB=True, crop=False)
  net.setInput(blob)
  start = time.time()
  layerOutputs = net.forward(ln)
  end = time.time()
  print("[INFO] YOLO took {:.6f} seconds".format(end - start))
  boxes = []
  confidences = []
  classIDs = []
  idd=[]
  for output in layerOutputs:
    for detection in output:
      scores = detection[5:]
      classID = np.argmax(scores)
      confidence = scores[classID]
      if confidence > 0.5:
        box = detection[0:4] * np.array([W, H, W, H])
        (centerX, centerY, width, height) = box.astype("int")
        x = int(centerX - (width / 2))
        y = int(centerY - (height / 2))
        boxes.append([x, y, int(width), int(height)])
        confidences.append(float(confidence))
        classIDs.append(classID)
        idd.append(classID)
  idxs = cv2.dnn.NMSBoxes(boxes, confidences, 0.5,
	0.3)
  if len(idxs) > 0:
    for i in idxs.flatten():
      (x, y) = (boxes[i][0], boxes[i][1])
      (w, h) = (boxes[i][2], boxes[i][3])
      color = [int(c) for c in COLORS[classIDs[i]]]
      cv2.rectangle(image, (x, y), (x + w, y + h), color, 2)
      text = "{}: {:.4f}".format(LABELS[classIDs[i]], confidences[i])
      cv2.putText(image, text, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX,
        0.5, color, 2)

[INFO] YOLO took 2.561785 seconds


In [1]:
#Image('image.jpg')
cv2.imwrite('C:\\Users\\Hp\\Desktop\\output.jpg', image)
display(Image('C:\\Users\\Hp\\Desktop\\output.jpg'))

NameError: name 'cv2' is not defined

In [13]:
st=[]
def CountFrequency(my_list): 
    freq = {} 
    kg=""
    for items in my_list: 
        freq[items] = my_list.count(items) 
    for key, value in freq.items(): 
        if(value>1):
            g="There are"+" "+str(value)+" "+ str(LABELS[key]+"s")
        else:
            g="There is"+" "+str(value)+" "+ str(LABELS[key])
        kg+=" "+g
    st.append(kg)
CountFrequency(idd)
print(st)

[' There are 2 frisbees There is 1 person There is 1 clock']


In [14]:
    mytext = st[0]
    language = 'en'
    myobj = gTTS(text=mytext, lang=language, slow=False)
    pat="C:\\Users\\Hp\\Desktop\speech\\obj.mp3"
    myobj.save(pat)
    os.system(pat)

gTTSError: Connection error during token calculation: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000029B72D2C2C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

In [14]:
import pytesseract as tess
tess.pytesseract.tesseract_cmd = r'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'
from PIL import Image

img = Image.open('C:\\Users\\Hp\\Desktop\\check.jfif')
textt = tess.image_to_string(img)
pathhh ="C:\\Users\\Hp\\Desktop\\check.jfif"
imagee = cv2.imread(pathhh)
#cv2.imshow("test", imagee)
print(textt)


we fall.
we breaks
we fail.

but then,
we rise.

we heal
we overcome.


In [15]:
mytex = textt
language = 'en'
myobj = gTTS(text=mytex, lang=language, slow=False)
pat="C:\\Users\\Hp\\Desktop\speech\\ocr.mp3"
myobj.save(pat)
os.system(pat)
    

0